FROM registry.opensuse.org/yast/head/containers/yast-ruby:latest

RUN zypper rm -y suseconnect-ng libsuseconnect suseconnect-ruby-bindings

# invalidate github cache
ADD https://api.github.com/repos/yast/yast-registration/git/refs/heads/master version.json

WORKDIR /yast-registration

RUN git clone --depth 1 https://github.com/yast/yast-registration.git /yast-registration

COPY out/libsuseconnect.so /usr/lib64
COPY yast/lib /usr/lib64/ruby/vendor_ruby/3.1.0
CMD ["rake", "test:unit"]

