---
name: agama tests

on: [pull_request]

env:
  CONNECTNG_SOURCE: /usr/src/connect-ng
  AGAMA_SOURCE: /usr/src/agama
  CONNECTNG_ARTIFACT: suseconnect-build-out
  CONNECTNG_TARBALL: /usr/src/suseconnect-build-out.tar.gz
  REGCODE: ${{ secrets.REGCODE }}
  RMT_HOST: ${{ secrets.RMT_HOST }}

jobs:

  build-suseconnect:
    name: Build SUSE/connect-ng inputs required by Agama
    runs-on: ubuntu-latest
    container:
      image: registry.suse.com/bci/golang:1.26-openssl
      options: --user root --privileged

    steps:
      - name: Install dependencies for artifact upload/download
        run: |
          zypper --non-interactive in nodejs-default

      - name: Checkout SUSE/connect-ng
        uses: actions/checkout@v4
        with:
          path: connect-ng

      - name: Move checked out connect-ng to /usr/src
        run: |
          mv connect-ng ${{ env.CONNECTNG_SOURCE }}

      - name: Build SUSE/connect-ng
        working-directory: ${{ env.CONNECTNG_SOURCE }}
        run: |
          make vendor build

      - name: Create a tarball of the build output
        working-directory: ${{ env.CONNECTNG_SOURCE }}
        run: |
          tar -czf ${CONNECTNG_TARBALL} out/

      - name: Upload the tarball
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CONNECTNG_ARTIFACT }}
          path: ${{ env.CONNECTNG_TARBALL }}
          retention-days: 1 # no need to retain this for long

  run-agama-rust-tests:
    name: Run agama rust tests
    needs: build-suseconnect
    runs-on: ubuntu-latest
    container:
      image: registry.suse.com/bci/rust:1.95
      options: --user root --privileged

    steps:
      - name: Install dependencies for artifact upload/download
        run: |
          zypper --non-interactive in nodejs-default

      - name: Checkout SUSE/connect-ng
        uses: actions/checkout@v4
        with:
          path: connect-ng

      - name: Move checked out connect-ng to /usr/src
        run: |
          mv connect-ng ${CONNECTNG_SOURCE}

      - name: Download suseconnect-build-out tarball
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.CONNECTNG_ARTIFACT }}
          path: /usr/src  # dirname of env.CONNECTNG_TARBALL

      - name: Extract tarball contents to expected location
        run: |
          tar -C ${CONNECTNG_SOURCE} -xzf ${CONNECTNG_TARBALL}

      - name: Checkout agama-project/agama
        uses: actions/checkout@v4
        with:
          repository: agama-project/agama
          path: agama

      - name: Move checked out agama code to /usr/src
        run: |
          mv agama ${AGAMA_SOURCE}

      - name: Run agama rust tests
        working-directory: ${{ env.CONNECTNG_SOURCE }}
        run: |
          build/ci/run-agama-rust-tests
