---
name: feature tests

on: [pull_request]

env:
  SOURCE: /usr/src/connect-ng
  ARTIFACT_SOURCE: artifacts
  COVERAGE_BIN: true
  REGCODE: ${{ secrets.REGCODE }}
  HA_REGCODE: ${{ secrets.HA_REGCODE }}
  EXPIRED_REGCODE: ${{ secrets.EXPIRED_REGCODE }}

jobs:
  feature-tests:
    runs-on: ubuntu-latest
    container:
      image: registry.suse.com/bci/golang:1.24-openssl
      options: --user root --privileged

    steps:
      - uses: actions/checkout@v4

      - name: move source to /usr/src/connect-ng
        run: |
          [ -d $SOURCE ] && rm -r $SOURCE
          cp -r $GITHUB_WORKSPACE $SOURCE

      - name: build suseconnect binaries
        run: |
          set -e
          cd $SOURCE
          make vendor
          make build

      - name: run feature tests
        run: |
          set -e
          cd $SOURCE
          make coverage-dirs
          bash build/ci/run-feature-tests

      - name: show feature tests coverage reports
        run: |
          set -e
          cd $SOURCE
          make feature-tests-coverage
