---
name: feature tests

on: [pull_request]

permissions:
  contents: read

env:
  SOURCE: /usr/src/connect-ng
  ARTIFACT_SOURCE: artifacts
  COVERAGE_BIN: true

jobs:
  feature-tests:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    container:
      image: registry.suse.com/bci/golang:1.26-openssl
      options: --user root --privileged

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: move source to /usr/src/connect-ng
        run: |
          [ -d $SOURCE ] && rm -r $SOURCE
          cp -r $GITHUB_WORKSPACE $SOURCE

      - name: build suseconnect binaries
        run: |
          set -e
          cd $SOURCE
          make vendor
          make build

      - name: run feature tests
        run: |
          set -e
          cd $SOURCE
          make coverage-dirs
          bash build/ci/run-feature-tests

      - name: show feature tests coverage reports
        run: |
          set -e
          cd $SOURCE
          make feature-tests-coverage
