name: lint

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - name: make lint
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          make lint
